name: Call both build workflows

on: 
    workflow_dispatch:

jobs:
    call-test:
     uses: seje-test-fabrik/elevopgave/.github/workflows/build_and_push_docker_image.yml@main

    call-build:
     uses: seje-test-fabrik/elevopgave/.github/workflows/build_and_push_docker_image_docker_cache.yml@main
